DROP TABLE IF EXISTS room;

CREATE TABLE room (
  ROOM_ID BIGINT(20) AUTO_INCREMENT  PRIMARY KEY ,
  Name VARCHAR(25) NOT NULL,
  Room_Number CHAR(3) NOT NULL,
  Size CHAR(4) NOT NULL
 );

  
DROP TABLE IF EXISTS GUEST;

CREATE TABLE GUEST(
  GUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  EMAIL_ADDRESS VARCHAR(50),
  ADDRESS VARCHAR(50),
  COUNTRY VARCHAR(30),
  STATE VARCHAR(10),
  PHONE_NUMBER VARCHAR(20)
);

  
DROP TABLE IF EXISTS RESERVATION;
CREATE TABLE RESERVATION(
  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  GUEST_ID BIGINT NOT NULL,
  RES_DATE DATE
);


ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES room(ROOM_ID);

ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);

CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);